// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.21.12
// source: c2.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	AgentService_Register_FullMethodName   = "/c2grpc.AgentService/Register"
	AgentService_Unregister_FullMethodName = "/c2grpc.AgentService/Unregister"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentServiceClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	Unregister(ctx context.Context, in *UnregisterRequest, opts ...grpc.CallOption) (*UnregisterResponse, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, AgentService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) Unregister(ctx context.Context, in *UnregisterRequest, opts ...grpc.CallOption) (*UnregisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnregisterResponse)
	err := c.cc.Invoke(ctx, AgentService_Unregister_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility
type AgentServiceServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	Unregister(context.Context, *UnregisterRequest) (*UnregisterResponse, error)
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAgentServiceServer struct {
}

func (UnimplementedAgentServiceServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedAgentServiceServer) Unregister(context.Context, *UnregisterRequest) (*UnregisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Unregister not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_Unregister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Unregister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Unregister_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Unregister(ctx, req.(*UnregisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "c2grpc.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _AgentService_Register_Handler,
		},
		{
			MethodName: "Unregister",
			Handler:    _AgentService_Unregister_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "c2.proto",
}

const (
	HeartbeatService_SendHeartbeat_FullMethodName = "/c2grpc.HeartbeatService/SendHeartbeat"
)

// HeartbeatServiceClient is the client API for HeartbeatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HeartbeatServiceClient interface {
	SendHeartbeat(ctx context.Context, opts ...grpc.CallOption) (HeartbeatService_SendHeartbeatClient, error)
}

type heartbeatServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHeartbeatServiceClient(cc grpc.ClientConnInterface) HeartbeatServiceClient {
	return &heartbeatServiceClient{cc}
}

func (c *heartbeatServiceClient) SendHeartbeat(ctx context.Context, opts ...grpc.CallOption) (HeartbeatService_SendHeartbeatClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HeartbeatService_ServiceDesc.Streams[0], HeartbeatService_SendHeartbeat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &heartbeatServiceSendHeartbeatClient{ClientStream: stream}
	return x, nil
}

type HeartbeatService_SendHeartbeatClient interface {
	Send(*HeartbeatRequest) error
	CloseAndRecv() (*HeartbeatSummary, error)
	grpc.ClientStream
}

type heartbeatServiceSendHeartbeatClient struct {
	grpc.ClientStream
}

func (x *heartbeatServiceSendHeartbeatClient) Send(m *HeartbeatRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *heartbeatServiceSendHeartbeatClient) CloseAndRecv() (*HeartbeatSummary, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(HeartbeatSummary)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// HeartbeatServiceServer is the server API for HeartbeatService service.
// All implementations must embed UnimplementedHeartbeatServiceServer
// for forward compatibility
type HeartbeatServiceServer interface {
	SendHeartbeat(HeartbeatService_SendHeartbeatServer) error
	mustEmbedUnimplementedHeartbeatServiceServer()
}

// UnimplementedHeartbeatServiceServer must be embedded to have forward compatible implementations.
type UnimplementedHeartbeatServiceServer struct {
}

func (UnimplementedHeartbeatServiceServer) SendHeartbeat(HeartbeatService_SendHeartbeatServer) error {
	return status.Errorf(codes.Unimplemented, "method SendHeartbeat not implemented")
}
func (UnimplementedHeartbeatServiceServer) mustEmbedUnimplementedHeartbeatServiceServer() {}

// UnsafeHeartbeatServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HeartbeatServiceServer will
// result in compilation errors.
type UnsafeHeartbeatServiceServer interface {
	mustEmbedUnimplementedHeartbeatServiceServer()
}

func RegisterHeartbeatServiceServer(s grpc.ServiceRegistrar, srv HeartbeatServiceServer) {
	s.RegisterService(&HeartbeatService_ServiceDesc, srv)
}

func _HeartbeatService_SendHeartbeat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HeartbeatServiceServer).SendHeartbeat(&heartbeatServiceSendHeartbeatServer{ServerStream: stream})
}

type HeartbeatService_SendHeartbeatServer interface {
	SendAndClose(*HeartbeatSummary) error
	Recv() (*HeartbeatRequest, error)
	grpc.ServerStream
}

type heartbeatServiceSendHeartbeatServer struct {
	grpc.ServerStream
}

func (x *heartbeatServiceSendHeartbeatServer) SendAndClose(m *HeartbeatSummary) error {
	return x.ServerStream.SendMsg(m)
}

func (x *heartbeatServiceSendHeartbeatServer) Recv() (*HeartbeatRequest, error) {
	m := new(HeartbeatRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// HeartbeatService_ServiceDesc is the grpc.ServiceDesc for HeartbeatService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HeartbeatService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "c2grpc.HeartbeatService",
	HandlerType: (*HeartbeatServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendHeartbeat",
			Handler:       _HeartbeatService_SendHeartbeat_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "c2.proto",
}

const (
	TaskService_ReceiveTasks_FullMethodName = "/c2grpc.TaskService/ReceiveTasks"
)

// TaskServiceClient is the client API for TaskService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TaskServiceClient interface {
	ReceiveTasks(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (TaskService_ReceiveTasksClient, error)
}

type taskServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTaskServiceClient(cc grpc.ClientConnInterface) TaskServiceClient {
	return &taskServiceClient{cc}
}

func (c *taskServiceClient) ReceiveTasks(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (TaskService_ReceiveTasksClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TaskService_ServiceDesc.Streams[0], TaskService_ReceiveTasks_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &taskServiceReceiveTasksClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TaskService_ReceiveTasksClient interface {
	Recv() (*Task, error)
	grpc.ClientStream
}

type taskServiceReceiveTasksClient struct {
	grpc.ClientStream
}

func (x *taskServiceReceiveTasksClient) Recv() (*Task, error) {
	m := new(Task)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TaskServiceServer is the server API for TaskService service.
// All implementations must embed UnimplementedTaskServiceServer
// for forward compatibility
type TaskServiceServer interface {
	ReceiveTasks(*TaskRequest, TaskService_ReceiveTasksServer) error
	mustEmbedUnimplementedTaskServiceServer()
}

// UnimplementedTaskServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTaskServiceServer struct {
}

func (UnimplementedTaskServiceServer) ReceiveTasks(*TaskRequest, TaskService_ReceiveTasksServer) error {
	return status.Errorf(codes.Unimplemented, "method ReceiveTasks not implemented")
}
func (UnimplementedTaskServiceServer) mustEmbedUnimplementedTaskServiceServer() {}

// UnsafeTaskServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaskServiceServer will
// result in compilation errors.
type UnsafeTaskServiceServer interface {
	mustEmbedUnimplementedTaskServiceServer()
}

func RegisterTaskServiceServer(s grpc.ServiceRegistrar, srv TaskServiceServer) {
	s.RegisterService(&TaskService_ServiceDesc, srv)
}

func _TaskService_ReceiveTasks_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TaskRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TaskServiceServer).ReceiveTasks(m, &taskServiceReceiveTasksServer{ServerStream: stream})
}

type TaskService_ReceiveTasksServer interface {
	Send(*Task) error
	grpc.ServerStream
}

type taskServiceReceiveTasksServer struct {
	grpc.ServerStream
}

func (x *taskServiceReceiveTasksServer) Send(m *Task) error {
	return x.ServerStream.SendMsg(m)
}

// TaskService_ServiceDesc is the grpc.ServiceDesc for TaskService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TaskService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "c2grpc.TaskService",
	HandlerType: (*TaskServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReceiveTasks",
			Handler:       _TaskService_ReceiveTasks_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "c2.proto",
}

const (
	OutputService_SendOutput_FullMethodName = "/c2grpc.OutputService/SendOutput"
)

// OutputServiceClient is the client API for OutputService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OutputServiceClient interface {
	SendOutput(ctx context.Context, opts ...grpc.CallOption) (OutputService_SendOutputClient, error)
}

type outputServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOutputServiceClient(cc grpc.ClientConnInterface) OutputServiceClient {
	return &outputServiceClient{cc}
}

func (c *outputServiceClient) SendOutput(ctx context.Context, opts ...grpc.CallOption) (OutputService_SendOutputClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OutputService_ServiceDesc.Streams[0], OutputService_SendOutput_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &outputServiceSendOutputClient{ClientStream: stream}
	return x, nil
}

type OutputService_SendOutputClient interface {
	Send(*OutputChunk) error
	CloseAndRecv() (*OutputAck, error)
	grpc.ClientStream
}

type outputServiceSendOutputClient struct {
	grpc.ClientStream
}

func (x *outputServiceSendOutputClient) Send(m *OutputChunk) error {
	return x.ClientStream.SendMsg(m)
}

func (x *outputServiceSendOutputClient) CloseAndRecv() (*OutputAck, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(OutputAck)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// OutputServiceServer is the server API for OutputService service.
// All implementations must embed UnimplementedOutputServiceServer
// for forward compatibility
type OutputServiceServer interface {
	SendOutput(OutputService_SendOutputServer) error
	mustEmbedUnimplementedOutputServiceServer()
}

// UnimplementedOutputServiceServer must be embedded to have forward compatible implementations.
type UnimplementedOutputServiceServer struct {
}

func (UnimplementedOutputServiceServer) SendOutput(OutputService_SendOutputServer) error {
	return status.Errorf(codes.Unimplemented, "method SendOutput not implemented")
}
func (UnimplementedOutputServiceServer) mustEmbedUnimplementedOutputServiceServer() {}

// UnsafeOutputServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OutputServiceServer will
// result in compilation errors.
type UnsafeOutputServiceServer interface {
	mustEmbedUnimplementedOutputServiceServer()
}

func RegisterOutputServiceServer(s grpc.ServiceRegistrar, srv OutputServiceServer) {
	s.RegisterService(&OutputService_ServiceDesc, srv)
}

func _OutputService_SendOutput_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(OutputServiceServer).SendOutput(&outputServiceSendOutputServer{ServerStream: stream})
}

type OutputService_SendOutputServer interface {
	SendAndClose(*OutputAck) error
	Recv() (*OutputChunk, error)
	grpc.ServerStream
}

type outputServiceSendOutputServer struct {
	grpc.ServerStream
}

func (x *outputServiceSendOutputServer) SendAndClose(m *OutputAck) error {
	return x.ServerStream.SendMsg(m)
}

func (x *outputServiceSendOutputServer) Recv() (*OutputChunk, error) {
	m := new(OutputChunk)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// OutputService_ServiceDesc is the grpc.ServiceDesc for OutputService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OutputService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "c2grpc.OutputService",
	HandlerType: (*OutputServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendOutput",
			Handler:       _OutputService_SendOutput_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "c2.proto",
}

const (
	OperatorService_Connect_FullMethodName = "/c2grpc.OperatorService/Connect"
)

// OperatorServiceClient is the client API for OperatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OperatorServiceClient interface {
	Connect(ctx context.Context, opts ...grpc.CallOption) (OperatorService_ConnectClient, error)
}

type operatorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOperatorServiceClient(cc grpc.ClientConnInterface) OperatorServiceClient {
	return &operatorServiceClient{cc}
}

func (c *operatorServiceClient) Connect(ctx context.Context, opts ...grpc.CallOption) (OperatorService_ConnectClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OperatorService_ServiceDesc.Streams[0], OperatorService_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &operatorServiceConnectClient{ClientStream: stream}
	return x, nil
}

type OperatorService_ConnectClient interface {
	Send(*OperatorCommand) error
	Recv() (*OperatorEvent, error)
	grpc.ClientStream
}

type operatorServiceConnectClient struct {
	grpc.ClientStream
}

func (x *operatorServiceConnectClient) Send(m *OperatorCommand) error {
	return x.ClientStream.SendMsg(m)
}

func (x *operatorServiceConnectClient) Recv() (*OperatorEvent, error) {
	m := new(OperatorEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// OperatorServiceServer is the server API for OperatorService service.
// All implementations must embed UnimplementedOperatorServiceServer
// for forward compatibility
type OperatorServiceServer interface {
	Connect(OperatorService_ConnectServer) error
	mustEmbedUnimplementedOperatorServiceServer()
}

// UnimplementedOperatorServiceServer must be embedded to have forward compatible implementations.
type UnimplementedOperatorServiceServer struct {
}

func (UnimplementedOperatorServiceServer) Connect(OperatorService_ConnectServer) error {
	return status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedOperatorServiceServer) mustEmbedUnimplementedOperatorServiceServer() {}

// UnsafeOperatorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OperatorServiceServer will
// result in compilation errors.
type UnsafeOperatorServiceServer interface {
	mustEmbedUnimplementedOperatorServiceServer()
}

func RegisterOperatorServiceServer(s grpc.ServiceRegistrar, srv OperatorServiceServer) {
	s.RegisterService(&OperatorService_ServiceDesc, srv)
}

func _OperatorService_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(OperatorServiceServer).Connect(&operatorServiceConnectServer{ServerStream: stream})
}

type OperatorService_ConnectServer interface {
	Send(*OperatorEvent) error
	Recv() (*OperatorCommand, error)
	grpc.ServerStream
}

type operatorServiceConnectServer struct {
	grpc.ServerStream
}

func (x *operatorServiceConnectServer) Send(m *OperatorEvent) error {
	return x.ServerStream.SendMsg(m)
}

func (x *operatorServiceConnectServer) Recv() (*OperatorCommand, error) {
	m := new(OperatorCommand)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// OperatorService_ServiceDesc is the grpc.ServiceDesc for OperatorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OperatorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "c2grpc.OperatorService",
	HandlerType: (*OperatorServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _OperatorService_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "c2.proto",
}

const (
	HistoryService_ListAgentHistory_FullMethodName = "/c2grpc.HistoryService/ListAgentHistory"
)

// HistoryServiceClient is the client API for HistoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HistoryServiceClient interface {
	ListAgentHistory(ctx context.Context, in *AgentHistoryRequest, opts ...grpc.CallOption) (*AgentHistoryResponse, error)
}

type historyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHistoryServiceClient(cc grpc.ClientConnInterface) HistoryServiceClient {
	return &historyServiceClient{cc}
}

func (c *historyServiceClient) ListAgentHistory(ctx context.Context, in *AgentHistoryRequest, opts ...grpc.CallOption) (*AgentHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentHistoryResponse)
	err := c.cc.Invoke(ctx, HistoryService_ListAgentHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HistoryServiceServer is the server API for HistoryService service.
// All implementations must embed UnimplementedHistoryServiceServer
// for forward compatibility
type HistoryServiceServer interface {
	ListAgentHistory(context.Context, *AgentHistoryRequest) (*AgentHistoryResponse, error)
	mustEmbedUnimplementedHistoryServiceServer()
}

// UnimplementedHistoryServiceServer must be embedded to have forward compatible implementations.
type UnimplementedHistoryServiceServer struct {
}

func (UnimplementedHistoryServiceServer) ListAgentHistory(context.Context, *AgentHistoryRequest) (*AgentHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAgentHistory not implemented")
}
func (UnimplementedHistoryServiceServer) mustEmbedUnimplementedHistoryServiceServer() {}

// UnsafeHistoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HistoryServiceServer will
// result in compilation errors.
type UnsafeHistoryServiceServer interface {
	mustEmbedUnimplementedHistoryServiceServer()
}

func RegisterHistoryServiceServer(s grpc.ServiceRegistrar, srv HistoryServiceServer) {
	s.RegisterService(&HistoryService_ServiceDesc, srv)
}

func _HistoryService_ListAgentHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoryServiceServer).ListAgentHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HistoryService_ListAgentHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoryServiceServer).ListAgentHistory(ctx, req.(*AgentHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HistoryService_ServiceDesc is the grpc.ServiceDesc for HistoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HistoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "c2grpc.HistoryService",
	HandlerType: (*HistoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListAgentHistory",
			Handler:    _HistoryService_ListAgentHistory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "c2.proto",
}

const (
	ShellService_AgentShell_FullMethodName    = "/c2grpc.ShellService/AgentShell"
	ShellService_OperatorShell_FullMethodName = "/c2grpc.ShellService/OperatorShell"
)

// ShellServiceClient is the client API for ShellService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShellServiceClient interface {
	AgentShell(ctx context.Context, opts ...grpc.CallOption) (ShellService_AgentShellClient, error)
	OperatorShell(ctx context.Context, opts ...grpc.CallOption) (ShellService_OperatorShellClient, error)
}

type shellServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewShellServiceClient(cc grpc.ClientConnInterface) ShellServiceClient {
	return &shellServiceClient{cc}
}

func (c *shellServiceClient) AgentShell(ctx context.Context, opts ...grpc.CallOption) (ShellService_AgentShellClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ShellService_ServiceDesc.Streams[0], ShellService_AgentShell_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &shellServiceAgentShellClient{ClientStream: stream}
	return x, nil
}

type ShellService_AgentShellClient interface {
	Send(*AgentShellEvent) error
	Recv() (*OperatorShellRequest, error)
	grpc.ClientStream
}

type shellServiceAgentShellClient struct {
	grpc.ClientStream
}

func (x *shellServiceAgentShellClient) Send(m *AgentShellEvent) error {
	return x.ClientStream.SendMsg(m)
}

func (x *shellServiceAgentShellClient) Recv() (*OperatorShellRequest, error) {
	m := new(OperatorShellRequest)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *shellServiceClient) OperatorShell(ctx context.Context, opts ...grpc.CallOption) (ShellService_OperatorShellClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ShellService_ServiceDesc.Streams[1], ShellService_OperatorShell_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &shellServiceOperatorShellClient{ClientStream: stream}
	return x, nil
}

type ShellService_OperatorShellClient interface {
	Send(*OperatorShellRequest) error
	Recv() (*AgentShellEvent, error)
	grpc.ClientStream
}

type shellServiceOperatorShellClient struct {
	grpc.ClientStream
}

func (x *shellServiceOperatorShellClient) Send(m *OperatorShellRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *shellServiceOperatorShellClient) Recv() (*AgentShellEvent, error) {
	m := new(AgentShellEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ShellServiceServer is the server API for ShellService service.
// All implementations must embed UnimplementedShellServiceServer
// for forward compatibility
type ShellServiceServer interface {
	AgentShell(ShellService_AgentShellServer) error
	OperatorShell(ShellService_OperatorShellServer) error
	mustEmbedUnimplementedShellServiceServer()
}

// UnimplementedShellServiceServer must be embedded to have forward compatible implementations.
type UnimplementedShellServiceServer struct {
}

func (UnimplementedShellServiceServer) AgentShell(ShellService_AgentShellServer) error {
	return status.Errorf(codes.Unimplemented, "method AgentShell not implemented")
}
func (UnimplementedShellServiceServer) OperatorShell(ShellService_OperatorShellServer) error {
	return status.Errorf(codes.Unimplemented, "method OperatorShell not implemented")
}
func (UnimplementedShellServiceServer) mustEmbedUnimplementedShellServiceServer() {}

// UnsafeShellServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShellServiceServer will
// result in compilation errors.
type UnsafeShellServiceServer interface {
	mustEmbedUnimplementedShellServiceServer()
}

func RegisterShellServiceServer(s grpc.ServiceRegistrar, srv ShellServiceServer) {
	s.RegisterService(&ShellService_ServiceDesc, srv)
}

func _ShellService_AgentShell_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ShellServiceServer).AgentShell(&shellServiceAgentShellServer{ServerStream: stream})
}

type ShellService_AgentShellServer interface {
	Send(*OperatorShellRequest) error
	Recv() (*AgentShellEvent, error)
	grpc.ServerStream
}

type shellServiceAgentShellServer struct {
	grpc.ServerStream
}

func (x *shellServiceAgentShellServer) Send(m *OperatorShellRequest) error {
	return x.ServerStream.SendMsg(m)
}

func (x *shellServiceAgentShellServer) Recv() (*AgentShellEvent, error) {
	m := new(AgentShellEvent)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _ShellService_OperatorShell_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ShellServiceServer).OperatorShell(&shellServiceOperatorShellServer{ServerStream: stream})
}

type ShellService_OperatorShellServer interface {
	Send(*AgentShellEvent) error
	Recv() (*OperatorShellRequest, error)
	grpc.ServerStream
}

type shellServiceOperatorShellServer struct {
	grpc.ServerStream
}

func (x *shellServiceOperatorShellServer) Send(m *AgentShellEvent) error {
	return x.ServerStream.SendMsg(m)
}

func (x *shellServiceOperatorShellServer) Recv() (*OperatorShellRequest, error) {
	m := new(OperatorShellRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ShellService_ServiceDesc is the grpc.ServiceDesc for ShellService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShellService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "c2grpc.ShellService",
	HandlerType: (*ShellServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AgentShell",
			Handler:       _ShellService_AgentShell_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "OperatorShell",
			Handler:       _ShellService_OperatorShell_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "c2.proto",
}

const (
	FileService_AgentTransfer_FullMethodName    = "/c2grpc.FileService/AgentTransfer"
	FileService_OperatorTransfer_FullMethodName = "/c2grpc.FileService/OperatorTransfer"
)

// FileServiceClient is the client API for FileService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FileServiceClient interface {
	AgentTransfer(ctx context.Context, opts ...grpc.CallOption) (FileService_AgentTransferClient, error)
	OperatorTransfer(ctx context.Context, opts ...grpc.CallOption) (FileService_OperatorTransferClient, error)
}

type fileServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFileServiceClient(cc grpc.ClientConnInterface) FileServiceClient {
	return &fileServiceClient{cc}
}

func (c *fileServiceClient) AgentTransfer(ctx context.Context, opts ...grpc.CallOption) (FileService_AgentTransferClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FileService_ServiceDesc.Streams[0], FileService_AgentTransfer_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &fileServiceAgentTransferClient{ClientStream: stream}
	return x, nil
}

type FileService_AgentTransferClient interface {
	Send(*AgentFileEvent) error
	Recv() (*OperatorFileRequest, error)
	grpc.ClientStream
}

type fileServiceAgentTransferClient struct {
	grpc.ClientStream
}

func (x *fileServiceAgentTransferClient) Send(m *AgentFileEvent) error {
	return x.ClientStream.SendMsg(m)
}

func (x *fileServiceAgentTransferClient) Recv() (*OperatorFileRequest, error) {
	m := new(OperatorFileRequest)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *fileServiceClient) OperatorTransfer(ctx context.Context, opts ...grpc.CallOption) (FileService_OperatorTransferClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FileService_ServiceDesc.Streams[1], FileService_OperatorTransfer_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &fileServiceOperatorTransferClient{ClientStream: stream}
	return x, nil
}

type FileService_OperatorTransferClient interface {
	Send(*OperatorFileRequest) error
	Recv() (*AgentFileEvent, error)
	grpc.ClientStream
}

type fileServiceOperatorTransferClient struct {
	grpc.ClientStream
}

func (x *fileServiceOperatorTransferClient) Send(m *OperatorFileRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *fileServiceOperatorTransferClient) Recv() (*AgentFileEvent, error) {
	m := new(AgentFileEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// FileServiceServer is the server API for FileService service.
// All implementations must embed UnimplementedFileServiceServer
// for forward compatibility
type FileServiceServer interface {
	AgentTransfer(FileService_AgentTransferServer) error
	OperatorTransfer(FileService_OperatorTransferServer) error
	mustEmbedUnimplementedFileServiceServer()
}

// UnimplementedFileServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFileServiceServer struct {
}

func (UnimplementedFileServiceServer) AgentTransfer(FileService_AgentTransferServer) error {
	return status.Errorf(codes.Unimplemented, "method AgentTransfer not implemented")
}
func (UnimplementedFileServiceServer) OperatorTransfer(FileService_OperatorTransferServer) error {
	return status.Errorf(codes.Unimplemented, "method OperatorTransfer not implemented")
}
func (UnimplementedFileServiceServer) mustEmbedUnimplementedFileServiceServer() {}

// UnsafeFileServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FileServiceServer will
// result in compilation errors.
type UnsafeFileServiceServer interface {
	mustEmbedUnimplementedFileServiceServer()
}

func RegisterFileServiceServer(s grpc.ServiceRegistrar, srv FileServiceServer) {
	s.RegisterService(&FileService_ServiceDesc, srv)
}

func _FileService_AgentTransfer_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FileServiceServer).AgentTransfer(&fileServiceAgentTransferServer{ServerStream: stream})
}

type FileService_AgentTransferServer interface {
	Send(*OperatorFileRequest) error
	Recv() (*AgentFileEvent, error)
	grpc.ServerStream
}

type fileServiceAgentTransferServer struct {
	grpc.ServerStream
}

func (x *fileServiceAgentTransferServer) Send(m *OperatorFileRequest) error {
	return x.ServerStream.SendMsg(m)
}

func (x *fileServiceAgentTransferServer) Recv() (*AgentFileEvent, error) {
	m := new(AgentFileEvent)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _FileService_OperatorTransfer_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FileServiceServer).OperatorTransfer(&fileServiceOperatorTransferServer{ServerStream: stream})
}

type FileService_OperatorTransferServer interface {
	Send(*AgentFileEvent) error
	Recv() (*OperatorFileRequest, error)
	grpc.ServerStream
}

type fileServiceOperatorTransferServer struct {
	grpc.ServerStream
}

func (x *fileServiceOperatorTransferServer) Send(m *AgentFileEvent) error {
	return x.ServerStream.SendMsg(m)
}

func (x *fileServiceOperatorTransferServer) Recv() (*OperatorFileRequest, error) {
	m := new(OperatorFileRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// FileService_ServiceDesc is the grpc.ServiceDesc for FileService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FileService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "c2grpc.FileService",
	HandlerType: (*FileServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AgentTransfer",
			Handler:       _FileService_AgentTransfer_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "OperatorTransfer",
			Handler:       _FileService_OperatorTransfer_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "c2.proto",
}
